### ISSUE TITLE
Recent Files

### ISSUE THREAD

**Issue by RobertBColton** [IsmAvatar/JEIE#10]
GM's does not have a recent files menu in the image editor because it is tightly integrated to the IDE. However this is still useful for quickly loading certain image files. @IsmAvatar What do you think?

**Comment by IsmAvatar** [comment]
I just wrote up a whole blurb about how that's not necessarily useful to a game dev, but then I realized we're talking about jeie.
Sounds good. See my comments about reusing code in the localization ticket.
