### ISSUE TITLE
Eraser Tool

### ISSUE THREAD

**Issue by RobertBColton** [IsmAvatar/JEIE#13]
This is a feature request, if approved I will implement the tools. I would like to add an erase tool with hardness and size, as well as a spray paint tool with the same options. I would also like to add size options to basic pencil tool. Please consider my feature request these seem like very basic tools, otherwise you really can't make parts of the image transparent, I had to load a transparent PNG to make sure JEIE does in fact support transparency unlike Paint (even in Windows 8 transparency is still not supported).

**Comment by IsmAvatar** [comment]
Make it so.
What's the difference between erase and draw using bg color with large brush?

**Comment by IsmAvatar** [comment]
For the erasor, I have no idea what that means. Sounds kind of complex. Are you sure it's still in the spirit of this program?
Anyways, I'm not going to stop you, just maybe reconsider, as it sounds like a bit of work and I'm not entirely sure what value it will bring.

Feel free to replace the icons with any set you feel is more appropriate. I originally just slapped some things on that I think I mostly drew myself, so obviously not intended to be permanent.

**Comment by IsmAvatar** [comment]
Ah, so it's for applying transparency to existing pixels. I see how that can be useful and difficult to implement at the same time.
So does the color picker color actually affect the eraser at all or just the transparency? Because in the latter case we could just add an intensity field and ignore the color picker.
