### ISSUE TITLE
Calico Icon Pack

### ISSUE THREAD

**Issue by RobertBColton** [IsmAvatar/JEIE#14]
@JoshDreamland would appreciate it if we used Calico as the default icon pack because it not only is vectorized and looks a lot better but we own the copyright. Calico is currently the default icon pack of LateralGM. https://github.com/enigma-dev/Calico-Icon

**Comment by RobertBColton** [comment]
@IsmAvatar Can you give some feedback here? What do you think about using Calico instead? Josh can make every icon we'll ever need.

**Comment by IsmAvatar** [comment]
I don't care. Sounds good. As I said before, the current icons were slapped together and temporary.

**Comment by RobertBColton** [comment]
@IsmAvatar Taken care of in #15 and the results are good.

![Calico Icons](https://cloud.githubusercontent.com/assets/3212801/5384316/7ae1a0fc-8086-11e4-9e24-737417c31028.png)
