### ISSUE TITLE
Internationalization and Localization

### ISSUE THREAD

**Issue by RobertBColton** [IsmAvatar/JEIE#8]
JEIE does not use a message bundle currently all strings are current NLS, the same goes for keyboard keystroke messages. @IsmAvatar Should I basically just implement this following the same policy as LateralGM?

**Comment by IsmAvatar** [comment]
I'm not really sure. How did we do it with JoshEdit?
I held off on this because I didn't want it to conflict with LateralGM and I didn't really want too much duplicate code either, as ideally it will be a part of LateralGM.
